# === Copyright
#
# Copyright (C) 2019  Atos SA Spain. All rights reserved.
#
# === License
#
# docker-compose.yaml is free software: you can redistribute it and/or modify it under the 
# terms of the Apache License, Version 2.0 (the License);
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# The software is provided "AS IS", without any warranty of any kind, express or implied,
# including but not limited to the warranties of merchantability, fitness for a particular
# purpose and noninfringement, in no event shall the authors or copyright holders be 
# liable for any claim, damages or other liability, whether in action of contract, tort or
# otherwise, arising from, out of or in connection with the software or the use or other
# dealings in the software.
# 
# See README file for the full disclaimer information and LICENSE file for full license 
# information in the project root.
# 
# == docker-compose.yml
#
# Service composition to deploy HAPI with keycloak and different databases for HAPI
#
# === Authors
#
# Author	Carlos Cavero
# 

version: '3'

services:
# MySQL database for HAPI
#  mysql:
#    image: mysql:5.7
#    container_name: mysql
##    volumes:
##      - ${CONFIG_FOLDER}/mysql/data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${DB_DB}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    healthcheck:
#        test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -p${DB_ROOT_PASSWORD} ping --silent"]
#        interval: 30s
#        timeout: 30s
#        retries: 3
#    restart: always

# PostgreSQL database for HAPI
  postgres:
    image: postgres:14-alpine3.15
    container_name: postgres
#    volumes:
#      - ${CONFIG_FOLDER}/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

# MariaDB database for HAPI
#  mariadb:
#    image: mariadb/server:10.3
#    container_name: mariadb
##    volumes:
##      - ${CONFIG_FOLDER}/mysql/data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${DB_DB}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    healthcheck:
#        test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -p${DB_ROOT_PASSWORD} ping --silent"]
#        interval: 30s
#        timeout: 30s
#        retries: 3
#    restart: always

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 9090:8080

#    restart: always

# CDR starter
  hapi-fhir:
    container_name: hapi-fhir
    build: .
    environment:
#       # Specify DB_VENDOR in .env if you want a non default db in HAPI
#      DB_VENDOR: ${DB_VENDOR}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_DATABASE: ${DB_DB}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
      OAUTH_URL: ${OAUTH_URL}  
      OAUTH_ENABLE: ${OAUTH_ENABLE}
      IMMUDB_BASE_URL: http://immugw:3323
      IMMUDB_USER: immu
      IMMUDB_PASSWORD: immu
    ports:
      - 8080:8080
    depends_on:
      - auth
#      - mysql
#      - mariadb
      - postgres
      - keycloak
      - immugw
    #restart: always

# Auth service
  auth:
    build:
      context: https://bitbucket.org/ihlchip/keycloak-auth-bch.git
    container_name: auth
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    ports:
      - 8081:8081
    depends_on:
      - keycloak
    #restart: always

  # Auth service
  provision-keycloak:
    container_name: provision-keycloak
    build:
        dockerfile: kcadm.Dockerfile
        context: .
    depends_on:
      - keycloak
    #restart: always


  immudb:
    image: codenotary/immudb:v0.6.2
    container_name: immudb
    environment:
      IMMUDB_NETWORK: tcp
      IMMUDB_ADDRESS: 0.0.0.0
      IMMUDB_AUTH: "true"
      IMMUDB_ADMIN_PASSWORD: "immu"
    expose:
      - "3322"
    ports:
      - "3322:3322"
      - "9497:9497"

  immugw:
    image: codenotary/immugw:v0.6.2
    container_name: immugw
    environment:
      IMMUGW_IMMUDB_ADDRESS: immudb
      IMMUGW_IMMUDB_PORT: 3322
    ports:
      - "3323:3323"
    depends_on:
      - immudb

  immudb-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: immudb-swagger
    environment:
      SWAGGER_JSON: "/openapi.json"
    ports:
      - "3380:8080"
    volumes:
      - ./immudb/immudb.schema.swagger.json:/openapi.json


